### ISSUE TITLE
typical environment variable values?

### ISSUE THREAD

**Issue by pibion** [zonca/docker-jupyter-cdms-light#5]
@zonca are there typical values you use for the environment variables `NB_UID`, `NB_USER`, and `CONDA_DIR`?

I'm assuming that `NB_USER` is usually `jovyan`, but I'm not sure what the others typically are.

**Comment by zonca** [comment]
they are set but the previous images, so I wouldn't worry about them. Only use them as variables.
CONDA_DIR I guess is `/opt/conda`

**Comment by pibion** [comment]
Okay, got it.  I'm getting an error when I `make build`:

```
The command '/bin/bash -o pipefail -c conda upgrade --quiet --yes --all &&     conda install --quiet --yes     'jupyterlab-system-monitor'     conda clean --all -f -y &&     rm -rf "/home/${NB_USER}/.cache/yarn" &&     rm -rf "/home/${NB_USER}/.node-gyp" &&     fix-permissions "${CONDA_DIR}" &&     fix-permissions "/home/${NB_USER}"' returned a non-zero code: 1
make: *** [Makefile:2: build] Error 1
```

And the source of the error appears to be difficulty finding `clean` from `conda`:

```
PackagesNotFoundError: The following packages are not available from current channels:

  - clean

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
```

@zonca do you get the same error?

**Comment by pibion** [comment]
I think I may have found the issue ... a missing &&?

I'm building now, will update!

**Comment by pibion** [comment]
That was it!  Fixed is pushed to my fork, I'll do a pull request once I've tried out some Makefile and README updates.
